# Generated by Django 3.2 on 2021-07-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='preview_images/'),
        ),
    ]
