# Generated by Django 3.2 on 2021-07-27 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='courses.lesson', unique=True),
        ),
    ]
